version: '3.8'
services:
  client:
    image: node:18
    container_name: client
    volumes:
      - ./client:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev && npm start"
    ports:
      - "3000:3000"

  server:
    image: golang:1.20
    container_name: server
    volumes:
      - ./server:/app
    working_dir: /app
    command: sh -c "go mod download && go run main.go"
    ports:
      - "5000:5000"
  
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
