name: CI
on:
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./client
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: npm i
            - name: Run ESLint
              run: npx eslint .
